import AsyncStorage from "@react-native-async-storage/async-storage";
import React, {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";
import { AppState } from "react-native";
import { useAuth } from "@clerk/expo";
import {
  getBadgeImageStatus,
  startBadgeImage,
  type BadgeImageStatus,
} from "@workspace/api-client-react";
import { badgeShareIndexKey } from "@/context/CollectionContext";

/**
 * Badge share images are generated by the API (gpt-image-2, ~20-60s) and stored
 * server-side, so a generation survives the user leaving the screen, closing
 * the app, or reinstalling. This context only tracks *which* badges the user
 * has asked for and polls their status; the image itself lives on the server.
 */

export type BadgeImageState = "none" | "pending" | "ready" | "failed";

interface BadgeShareContextValue {
  /** Current generation state for a badge. */
  getStatus: (badgeId: string) => BadgeImageState;
  /** Kicks off generation. Returns the state right after the request. */
  requestImage: (
    badgeId: string,
    breeds: string[],
    totalCollected: number,
    regenerate?: boolean,
  ) => Promise<BadgeImageState>;
  /** True while the initial status lookup for known badges is in flight. */
  isRestoring: boolean;
}

const BadgeShareContext = createContext<BadgeShareContextValue>({
  getStatus: () => "none",
  requestImage: async () => "none",
  isRestoring: false,
});

const POLL_MS = 8000;

export function BadgeShareProvider({ children }: { children: React.ReactNode }) {
  const { userId, isLoaded: authLoaded } = useAuth();
  const [statuses, setStatuses] = useState<Record<string, BadgeImageState>>({});
  const [isRestoring, setIsRestoring] = useState(false);
  // Account the in-memory statuses belong to, so a late response from a
  // previous account can never be written into the current one's state.
  const ownerRef = useRef<string | null>(null);

  const persistRequested = useCallback(
    async (uid: string, badgeIds: string[]) => {
      await AsyncStorage.setItem(
        badgeShareIndexKey(uid),
        JSON.stringify(badgeIds),
      ).catch(() => {});
    },
    [],
  );

  // On sign-in, re-check every badge the user previously asked for. This is
  // what makes "come back later" work after the app was closed entirely.
  useEffect(() => {
    if (!authLoaded) return;

    ownerRef.current = null;
    setStatuses({});

    if (!userId) return;

    let cancelled = false;
    setIsRestoring(true);

    (async () => {
      let requested: string[] = [];
      try {
        const raw = await AsyncStorage.getItem(badgeShareIndexKey(userId));
        if (raw) {
          const parsed = JSON.parse(raw);
          // Older builds stored a { [medalId]: {...} } map of local captures.
          requested = Array.isArray(parsed) ? parsed : Object.keys(parsed ?? {});
        }
      } catch {
        requested = [];
      }

      ownerRef.current = userId;

      const results = await Promise.all(
        requested.map(async (badgeId) => {
          try {
            const res = await getBadgeImageStatus(badgeId);
            return [badgeId, (res.status ?? "none") as BadgeImageState] as const;
          } catch {
            return [badgeId, "none"] as const;
          }
        }),
      );

      if (cancelled || ownerRef.current !== userId) return;
      setStatuses(Object.fromEntries(results.filter(([, s]) => s !== "none")));
      setIsRestoring(false);
    })();

    return () => {
      cancelled = true;
      setIsRestoring(false);
    };
  }, [userId, authLoaded]);

  const pendingIds = useMemo(
    () => Object.keys(statuses).filter((id) => statuses[id] === "pending"),
    [statuses],
  );
  // Keep the poll effect from re-subscribing on every unrelated state change.
  const pendingKey = pendingIds.join(",");

  // Poll while anything is generating, and re-check on foreground so a user
  // returning to the app sees a finished image immediately.
  useEffect(() => {
    if (!userId || pendingKey.length === 0) return;

    let cancelled = false;

    const check = async () => {
      const ids = pendingKey.split(",");
      const results = await Promise.all(
        ids.map(async (badgeId) => {
          try {
            const res: BadgeImageStatus = await getBadgeImageStatus(badgeId);
            return [badgeId, (res.status ?? "pending") as BadgeImageState] as const;
          } catch {
            return null;
          }
        }),
      );
      if (cancelled || ownerRef.current !== userId) return;
      const settled = results.filter(
        (r): r is readonly [string, BadgeImageState] => r !== null,
      );
      if (settled.length === 0) return;
      setStatuses((prev) => {
        const next = { ...prev };
        for (const [id, status] of settled) next[id] = status;
        return next;
      });
    };

    const interval = setInterval(check, POLL_MS);
    const sub = AppState.addEventListener("change", (state) => {
      if (state === "active") check();
    });

    return () => {
      cancelled = true;
      clearInterval(interval);
      sub.remove();
    };
  }, [pendingKey, userId]);

  const requestImage = useCallback(
    async (
      badgeId: string,
      breeds: string[],
      totalCollected: number,
      regenerate = false,
    ): Promise<BadgeImageState> => {
      if (!userId) return "none";
      try {
        const res = await startBadgeImage({
          badgeId,
          breeds,
          totalCollected,
          regenerate,
        });
        const status = (res.status ?? "pending") as BadgeImageState;
        if (ownerRef.current === userId) {
          setStatuses((prev) => {
            const next = { ...prev, [badgeId]: status };
            void persistRequested(userId, Object.keys(next));
            return next;
          });
        }
        return status;
      } catch {
        return "failed";
      }
    },
    [userId, persistRequested],
  );

  const getStatus = useCallback(
    (badgeId: string): BadgeImageState => statuses[badgeId] ?? "none",
    [statuses],
  );

  const value = useMemo(
    () => ({ getStatus, requestImage, isRestoring }),
    [getStatus, requestImage, isRestoring],
  );

  return (
    <BadgeShareContext.Provider value={value}>
      {children}
    </BadgeShareContext.Provider>
  );
}

export function useBadgeShare() {
  return useContext(BadgeShareContext);
}
