// Additional PawDex breed catalog entries.
// Same shape/tone as the DOG_BREEDS literal in dogs.ts; spread into the served catalog.
export const DOG_BREEDS_EXTRA = [
  {
    id: "affenpinscher", name: "Affenpinscher",
    description: "The 'Monkey Terrier'! This tiny, mustachioed ragamuffin was bred to hunt rats in German kitchens and carries itself like a comedic little general.",
    origin: "Germany", size: "small" as const, temperament: "Confident, Famously Funny, Fearless", lifespan: "12-15 years", imageUrl: "https://images.dog.ceo/breeds/affenpinscher/n02110627_10185.jpg", group: "Toy", rarity: "rare" as const,
    personality: "Tiny clown convinced it's a Rottweiler",
    humanJob: "Improv comedian who genuinely thinks they're wise",
    coffeeOrder: "Tiny espresso, drunk with maximum drama",
    ancestors: "Small German ratting terriers of the 1600s, refined into a wiry-coated companion whose name means 'monkey terrier'",
    funFact: "The Affenpinscher's shaggy face and expressive eyebrows earned it the nickname 'diablotin moustachu' — the mustached little devil — in France",
    popCulture: "Banana Joe won Best in Show at Westminster in 2013, the first Affenpinscher ever to take the top prize",
    energyLevel: 3, apartmentFriendly: 5, chaosLevel: 3,
    randomLore: "Affenpinschers are believed to be an ancestor of both the Brussels Griffon and the Miniature Schnauzer",
  },
  {
    id: "schipperke", name: "Schipperke",
    description: "The 'Little Captain'! A tailless black spitz from Belgium that patrolled canal barges hunting vermin — endless energy packed into a fox-like frame.",
    origin: "Belgium", size: "small" as const, temperament: "Curious, Confident, Mischievous", lifespan: "13-15 years", imageUrl: "https://images.dog.ceo/breeds/schipperke/middy.jpg", group: "Non-Sporting", rarity: "rare" as const,
    personality: "Restless little foreman who supervises everything",
    humanJob: "Ship's boatswain who never sits down",
    coffeeOrder: "Double cold brew, needs the extra jitters",
    ancestors: "Descended from a black Belgian sheepdog called the Leauvenaar, shrunk down into a compact barge-and-workshop guardian",
    funFact: "Many Schipperkes are born tailless, and their thick ruff and 'culottes' on the hind legs give them a distinctive silhouette that looks like a little black fox",
    popCulture: "A favorite of Belgian tradesmen and canal boatmen, the breed's name is thought to mean 'little boatman' in Flemish",
    energyLevel: 5, apartmentFriendly: 3, chaosLevel: 4,
    randomLore: "In 1690 a guild of Brussels shoemakers held what may be the world's first specialty dog show — for Schipperkes, judged on their ornate brass collars",
  },
  {
    id: "australian-terrier", name: "Australian Terrier",
    description: "One of the smallest working terriers! This rugged little Aussie was bred to guard mines, tend sheep, and kill snakes and rodents in the outback.",
    origin: "Australia", size: "small" as const, temperament: "Spirited, Alert, Courageous", lifespan: "11-15 years", imageUrl: "https://images.dog.ceo/breeds/terrier-australian/fb_img_1596625396617.jpg", group: "Terrier", rarity: "rare" as const,
    personality: "Scrappy outback deputy with big opinions",
    humanJob: "Ranch hand who fixes fences and fears nothing",
    coffeeOrder: "Long black, sipped on the porch at dawn",
    ancestors: "A blend of British terriers — Cairn, Dandie Dinmont, Yorkshire and others — brought by settlers and adapted to harsh Australian conditions",
    funFact: "It was the first native Australian breed to be recognized and shown, and its harsh weatherproof coat helped it survive the extreme outback climate",
    popCulture: "Long a symbol of the resourceful Australian bush dog, valued by settlers as an all-purpose farm and family companion",
    energyLevel: 4, apartmentFriendly: 4, chaosLevel: 3,
    randomLore: "Aussie Terriers were prized for their courage against snakes, and legend holds they'd take on brown snakes many times their own length",
  },
  {
    id: "welsh-springer-spaniel", name: "Welsh Springer Spaniel",
    description: "The 'Welsh Cocker'! A ruby-and-white gundog that has changed little in centuries — devoted, tireless, and built for a full day's work in the field.",
    origin: "Wales", size: "medium" as const, temperament: "Loyal, Affectionate, Hardworking", lifespan: "12-15 years", imageUrl: "https://images.dog.ceo/breeds/spaniel-welsh/n02102177_1022.jpg", group: "Sporting", rarity: "rare" as const,
    personality: "Devoted field partner who velcros to your leg",
    humanJob: "Trail guide who knows every ridge in the valley",
    coffeeOrder: "Flat white, to go, already lacing up boots",
    ancestors: "An ancient British land spaniel type depicted in Welsh art for centuries, distinct from the English Springer since at least the 1700s",
    funFact: "Its distinctive rich red-and-white coat is a breed hallmark, and it's often called the Welsh Cocker for its older regional name",
    popCulture: "One of Britain's oldest spaniel breeds, it appears in tapestries and paintings dating back hundreds of years",
    energyLevel: 4, apartmentFriendly: 2, chaosLevel: 3,
    randomLore: "Dogs resembling the Welsh Springer were recorded in Welsh laws as far back as 1300, making it one of the oldest documented spaniel types",
  },
  {
    id: "curly-coated-retriever", name: "Curly-Coated Retriever",
    description: "The oldest of the retrievers! A tall, dignified gundog covered head to tail in tight water-resistant curls, equally at home in duck marsh or drawing room.",
    origin: "England", size: "large" as const, temperament: "Confident, Independent, Loyal", lifespan: "10-12 years", imageUrl: "https://images.dog.ceo/breeds/retriever-curly/n02099429_1039.jpg", group: "Sporting", rarity: "rare" as const,
    personality: "Aloof aristocrat who secretly adores swimming",
    humanJob: "Reserved professor who owns three lakeside cabins",
    coffeeOrder: "Pour-over, black, appreciated in silence",
    ancestors: "Believed to descend from the English Water Spaniel and retrieving setters, later crossed with Poodles to tighten the curls",
    funFact: "The tight curls act like a wetsuit, shedding water and shrugging off brambles, making it a superb retriever in cold water and heavy cover",
    popCulture: "Considered by many historians to be the oldest of all retriever breeds, dating to the late 1700s",
    energyLevel: 4, apartmentFriendly: 2, chaosLevel: 3,
    randomLore: "It was one of the first breeds exhibited at England's very first dog show in 1860",
  },
  {
    id: "staffordshire-bull-terrier", name: "Staffordshire Bull Terrier",
    description: "The 'Nanny Dog'! Muscular and famously affectionate, the Staffie is a devoted family companion beloved across Britain for its patience with children.",
    origin: "England", size: "medium" as const, temperament: "Affectionate, Brave, Reliable", lifespan: "12-14 years", imageUrl: "https://images.dog.ceo/breeds/bullterrier-staffordshire/20200820_131119.jpg", group: "Terrier", rarity: "uncommon" as const,
    personality: "Muscly cuddle machine that grins constantly",
    humanJob: "Gentle bouncer who volunteers at the daycare",
    coffeeOrder: "Builder's tea, honestly, forget the coffee",
    ancestors: "A cross of the old English Bulldog and terriers in the mining regions of Staffordshire, later bred away from fighting into a beloved companion",
    funFact: "Its long-standing reputation as a 'nanny dog' comes from its remarkable gentleness and patience with children in working-class British homes",
    popCulture: "One of the most popular breeds in the United Kingdom and a recurring symbol of the loyal British family dog",
    energyLevel: 4, apartmentFriendly: 3, chaosLevel: 3,
    randomLore: "The breed wasn't recognized by the Kennel Club until 1935, decades after dog fighting was outlawed and fanciers worked to rehabilitate its image",
  },
  {
    id: "norwich-terrier", name: "Norwich Terrier",
    description: "One of the tiniest terriers with the biggest heart! Prick-eared and fearless, this English ratter was once the mascot of Cambridge students.",
    origin: "England", size: "small" as const, temperament: "Affectionate, Sensible, Fearless", lifespan: "12-15 years", imageUrl: "https://images.dog.ceo/breeds/terrier-norwich/n02094258_1003.jpg", group: "Terrier", rarity: "rare" as const,
    personality: "Pint-sized daredevil with a permanent grin",
    humanJob: "Cambridge undergrad who dares anyone to anything",
    coffeeOrder: "Small mocha, extra whipped cream",
    ancestors: "Small ratting terriers of East Anglia, sharing early roots with the Norfolk Terrier until the two were split by ear type",
    funFact: "The Norwich has upright prick ears, while its near-identical cousin the Norfolk has folded drop ears — that single difference separated them into two breeds in 1964",
    popCulture: "Became a fashionable mascot among Cambridge University students in the early 1900s, cementing its 'college dog' reputation",
    energyLevel: 4, apartmentFriendly: 5, chaosLevel: 3,
    randomLore: "For decades the Norwich and Norfolk were the same breed, differing only in whether their ears stood up or flopped down",
  },
  {
    id: "tibetan-terrier", name: "Tibetan Terrier",
    description: "The 'Holy Dog of Tibet'! Not actually a terrier, this shaggy monastery companion was raised as a good-luck charm and never sold — only given as a gift.",
    origin: "Tibet", size: "medium" as const, temperament: "Affectionate, Loyal, Sensitive", lifespan: "15-16 years", imageUrl: "https://images.dog.ceo/breeds/terrier-tibetan/n02097474_1023.jpg", group: "Non-Sporting", rarity: "rare" as const,
    personality: "Serene old soul with a mountain of hair",
    humanJob: "Monastery caretaker and part-time weather forecaster",
    coffeeOrder: "Butter tea, obviously, this is a Himalayan dog",
    ancestors: "Kept for two thousand years by Tibetan monks in mountain monasteries as companions and good-luck charms, not as working terriers",
    funFact: "Its large, flat, snowshoe-like feet evolved to distribute weight and grip on snow and rocky Himalayan terrain",
    popCulture: "Revered as bringers of good fortune, Tibetan Terriers were traditionally never sold — only given as gifts to honored guests",
    energyLevel: 3, apartmentFriendly: 4, chaosLevel: 2,
    randomLore: "The 'terrier' label was a mistake by Western visitors who judged it by size alone — it has no terrier ancestry whatsoever",
  },
  {
    id: "norfolk-terrier", name: "Norfolk Terrier",
    description: "A demon on legs in a tiny body! One of the smallest working terriers, the drop-eared Norfolk was bred to bolt foxes and clear barns of rats.",
    origin: "England", size: "small" as const, temperament: "Fearless, Merry, Companionable", lifespan: "12-16 years", imageUrl: "https://images.dog.ceo/breeds/terrier-norfolk/20201118-norfolk.jpg", group: "Terrier", rarity: "rare" as const,
    personality: "Cheerful little bulldozer with folded ears",
    humanJob: "Pest-control expert who's weirdly cheerful about it",
    coffeeOrder: "Flat white, downed in one confident gulp",
    ancestors: "East Anglian ratting terriers shared with the Norwich, split off in 1964 by their distinctive drop ears",
    funFact: "The Norfolk's ears fold neatly forward, the single feature that distinguishes it from the prick-eared Norwich Terrier it was once bundled with",
    popCulture: "Long favored by fox hunts to work alongside hounds, small enough to dig into a den yet gritty enough to face the quarry",
    energyLevel: 4, apartmentFriendly: 5, chaosLevel: 3,
    randomLore: "Norfolks were nicknamed 'the perfect demon' by the hunters who prized their gameness against foxes many times their size",
  },
  {
    id: "border-terrier", name: "Border Terrier",
    description: "The scruffy hunter with an otter-shaped head! Bred to run with foxhounds along the Scottish-English border, this terrier has the legs and stamina to keep up.",
    origin: "United Kingdom", size: "small" as const, temperament: "Affectionate, Happy, Plucky", lifespan: "12-15 years", imageUrl: "https://images.dog.ceo/breeds/terrier-border/n02093754_1062.jpg", group: "Terrier", rarity: "uncommon" as const,
    personality: "Tireless country rambler with an otter face",
    humanJob: "Marathon runner who also fixes your plumbing",
    coffeeOrder: "Filter coffee in a thermos, halfway up a hill",
    ancestors: "Developed in the hilly border country between England and Scotland to run with hounds and go to ground after foxes",
    funFact: "Its distinctive 'otter-shaped' head and long legs let it keep pace with mounted hunts, then squeeze into fox dens to flush the quarry",
    popCulture: "A perennial British favorite, the Border Terrier played Baxter in 'Anchorman' and Puffy in 'There's Something About Mary'",
    energyLevel: 4, apartmentFriendly: 4, chaosLevel: 3,
    randomLore: "The breed's harsh double coat and loose, thick hide were purpose-built to shrug off cold border weather and the bites of cornered foxes",
  },
  {
    id: "irish-terrier", name: "Irish Terrier",
    description: "The 'Daredevil'! A fiery red terrier from Ireland famed for reckless courage — it served as a messenger and sentinel dog in the trenches of WWI.",
    origin: "Ireland", size: "medium" as const, temperament: "Bold, Dashing, Tenderhearted", lifespan: "13-15 years", imageUrl: "https://images.dog.ceo/breeds/terrier-irish/n02093991_1026.jpg", group: "Terrier", rarity: "rare" as const,
    personality: "Hot-headed romantic with a blazing red coat",
    humanJob: "War correspondent who's also a hopeless softie",
    coffeeOrder: "Irish coffee, and no you can't talk him out of it",
    ancestors: "One of the oldest terrier breeds, developed in Ireland from old black-and-tan and wheaten terrier stock",
    funFact: "Irish Terriers served with distinction as WWI messenger and sentinel dogs, calmly carrying dispatches across battlefields under heavy fire",
    popCulture: "Star of the classic film 'Firehouse Dog,' and long celebrated in Ireland for their fearless, devil-may-care spirit",
    energyLevel: 4, apartmentFriendly: 3, chaosLevel: 4,
    randomLore: "Its solid red coat is a breed signature — Irish Terriers should be a whole-colored bright red, wheaten-red, or golden-red with no markings",
  },
  {
    id: "redbone-coonhound", name: "Redbone Coonhound",
    description: "A flashy solid-red hound with a musical bawl! Bred in the American South to tree raccoons at night, it's as sweet at home as it is relentless on a trail.",
    origin: "United States", size: "large" as const, temperament: "Even-Tempered, Amiable, Eager", lifespan: "12-15 years", imageUrl: "https://images.dog.ceo/breeds/redbone/n02090379_1006.jpg", group: "Hound", rarity: "rare" as const,
    personality: "Laid-back tracker who howls like an opera singer",
    humanJob: "Night-shift game warden with a killer singing voice",
    coffeeOrder: "Cowboy coffee, boiled over a campfire",
    ancestors: "Bred from red foxhounds brought by Scottish immigrants, later crossed with Bloodhounds to sharpen its cold-nose tracking",
    funFact: "Redbones are versatile trailers that work everything from raccoons to bears and cougars, and their solid red coat makes them one of the most striking coonhounds",
    popCulture: "Immortalized as Old Dan and Little Ann in the beloved novel and film 'Where the Red Fern Grows'",
    energyLevel: 4, apartmentFriendly: 2, chaosLevel: 3,
    randomLore: "The 'bone' in Redbone likely honors early breeder Peter Redbone of Tennessee rather than describing the dog itself",
  },
  {
    id: "brussels-griffon", name: "Brussels Griffon",
    description: "A whiskery little human in a dog suit! This Belgian toy has an almost comically expressive, near-human face and an outsized, sensitive personality.",
    origin: "Belgium", size: "small" as const, temperament: "Loyal, Alert, Curious", lifespan: "12-15 years", imageUrl: "https://images.dog.ceo/breeds/brabancon/n02112706_1041.jpg", group: "Toy", rarity: "rare" as const,
    personality: "Melodramatic tiny philosopher, deeply offended easily",
    humanJob: "Bearded theater actor who takes everything personally",
    coffeeOrder: "Cortado, sipped while contemplating existence",
    ancestors: "Descended from small Belgian stable terriers called Griffons d'Ecurie that kept coach houses free of rats, refined with Affenpinscher and Pug",
    funFact: "Its remarkably human-like, expressive face inspired the design of the alien Yoda-style creatures and won it fans who swear it understands every word you say",
    popCulture: "Verdell the Brussels Griffon nearly stole the movie 'As Good as It Gets' opposite Jack Nicholson",
    energyLevel: 3, apartmentFriendly: 5, chaosLevel: 3,
    randomLore: "The breed nearly vanished during the two World Wars, surviving thanks to a handful of dedicated Belgian and British breeders",
  },
  {
    id: "dandie-dinmont-terrier", name: "Dandie Dinmont Terrier",
    description: "The only breed named after a fictional character! A long-bodied terrier with a signature fluffy topknot, immortalized by a Sir Walter Scott novel.",
    origin: "United Kingdom", size: "small" as const, temperament: "Independent, Smart, Dignified", lifespan: "12-15 years", imageUrl: "https://images.dog.ceo/breeds/terrier-dandie/n02096437_1006.jpg", group: "Terrier", rarity: "legendary" as const,
    personality: "Distinguished eccentric with a magnificent pouf",
    humanJob: "Retired novelist with a truly excellent hat",
    coffeeOrder: "Single-origin Ethiopian, discussed at length",
    ancestors: "An old Border-country terrier bred to hunt otters and badgers, kept by farmers and gypsies along the Scottish-English frontier",
    funFact: "It's the only dog breed named after a fictional character — Dandie Dinmont, a farmer in Sir Walter Scott's 1815 novel 'Guy Mannering'",
    popCulture: "After Scott's novel featured the dogs, they became so fashionable that the breed took its name from the book — a literary first in the dog world",
    energyLevel: 3, apartmentFriendly: 4, chaosLevel: 2,
    randomLore: "Now one of the rarest breeds in Britain, only a few dozen puppies are registered with the Kennel Club each year, making it a 'vulnerable native breed'",
  },
  {
    id: "sealyham-terrier", name: "Sealyham Terrier",
    description: "A vanishing aristocrat of terriers! Once the height of Hollywood glamour, this stocky white Welsh badger-dog is now among Britain's rarest breeds.",
    origin: "Wales", size: "small" as const, temperament: "Alert, Outgoing, Calm", lifespan: "12-14 years", imageUrl: "https://images.dog.ceo/breeds/terrier-sealyham/n02095889_1003.jpg", group: "Terrier", rarity: "legendary" as const,
    personality: "Faded film star who still expects the spotlight",
    humanJob: "Old-Hollywood costume designer, gloriously out of fashion",
    coffeeOrder: "A martini, actually — coffee is so pedestrian",
    ancestors: "Created in the 1850s by Captain John Edwardes at his Sealyham estate in Wales to hunt badgers, otters and foxes",
    funFact: "In the 1920s and 30s it was one of the most fashionable breeds in the world, owned by Alfred Hitchcock, Cary Grant, Humphrey Bogart and Elizabeth Taylor",
    popCulture: "Hitchcock adored his Sealyhams so much he gave himself a cameo walking two of them in his film 'The Birds'",
    energyLevel: 3, apartmentFriendly: 4, chaosLevel: 2,
    randomLore: "Despite its glamorous past, it's now listed as a vulnerable native breed in the UK, with only a handful of puppies registered annually",
  },
  {
    id: "bedlington-terrier", name: "Bedlington Terrier",
    description: "A lamb with the heart of a lion! This pear-headed, curly-coated terrier looks like a woolly little sheep but was bred to kill vermin with ferocious speed.",
    origin: "England", size: "medium" as const, temperament: "Good-Tempered, Energetic, Loyal", lifespan: "11-16 years", imageUrl: "https://images.dog.ceo/breeds/terrier-bedlington/n02093647_1022.jpg", group: "Terrier", rarity: "rare" as const,
    personality: "Gentle sheep-lookalike with a hidden mean streak",
    humanJob: "Soft-spoken shepherd who moonlights as a boxer",
    coffeeOrder: "Almond milk latte, in a wool-warmed mug",
    ancestors: "Bred by miners in Northumberland from local terriers, possibly with Whippet blood, to race and to hunt rats and rabbits",
    funFact: "Its lamb-like appearance is entirely deceptive — the Bedlington is fast, athletic, and was once used in the pits for ratting contests",
    popCulture: "The unmistakable 'dog that looks like a sheep' has long been a favorite subject of Victorian art and modern internet fascination",
    energyLevel: 4, apartmentFriendly: 4, chaosLevel: 3,
    randomLore: "It was originally called the Rothbury Terrier before taking the name of the mining town of Bedlington around 1825",
  },
  {
    id: "lhasa-apso", name: "Lhasa Apso",
    description: "A sacred sentinel of Tibetan temples! For over a thousand years this long-coated little watchdog guarded palaces and monasteries in the Himalayas.",
    origin: "Tibet", size: "small" as const, temperament: "Confident, Devoted, Comical", lifespan: "12-15 years", imageUrl: "https://images.dog.ceo/breeds/lhasa/n02098413_10144.jpg", group: "Non-Sporting", rarity: "uncommon" as const,
    personality: "Tiny temple guardian with an enormous ego",
    humanJob: "Palace security chief who's slightly too dramatic",
    coffeeOrder: "Butter tea, served on a silk cushion",
    ancestors: "An ancient Tibetan breed kept by monks and nobles as indoor sentinels behind the outer Tibetan Mastiff guard dogs",
    funFact: "Its name derives from Lhasa, the sacred Tibetan capital, and 'apso,' loosely meaning long-haired or bearded dog",
    popCulture: "The Dalai Lama traditionally sent Lhasa Apsos as prized gifts, and they were long believed to house the souls of departed lamas",
    energyLevel: 2, apartmentFriendly: 5, chaosLevel: 2,
    randomLore: "Tibetans believed a well-bred Lhasa Apso could bring good fortune to a household — and they were never sold, only bestowed as honored gifts",
  },
  {
    id: "lakeland-terrier", name: "Lakeland Terrier",
    description: "A fearless fell-runner! Bred in England's rugged Lake District to protect flocks by hunting down foxes among the crags — small, sturdy, and utterly bold.",
    origin: "England", size: "small" as const, temperament: "Bold, Friendly, Confident", lifespan: "12-15 years", imageUrl: "https://images.dog.ceo/breeds/terrier-lakeland/n02095570_1031.jpg", group: "Terrier", rarity: "rare" as const,
    personality: "Bouncy mountaineer who fears absolutely nothing",
    humanJob: "Rock climber who free-solos for fun",
    coffeeOrder: "Espresso shot chugged before the summit push",
    ancestors: "Developed by Lake District farmers from Border, Bedlington and Fox terrier stock to run with hounds and go to ground after fell foxes",
    funFact: "Lakelands are famed for their nerve underground — they were bred to follow foxes deep into rocky dens and even endure being dug out over hours",
    popCulture: "Stingray of Derryabah won Best in Show at both Westminster and Crufts, a rare transatlantic double for any breed",
    energyLevel: 4, apartmentFriendly: 3, chaosLevel: 4,
    randomLore: "Lake District shepherds prized these terriers for guarding lambs, since a single fox could devastate a hill flock during lambing season",
  },
  {
    id: "american-staffordshire-terrier", name: "American Staffordshire Terrier",
    description: "The confident 'AmStaff'! A muscular, courageous, and famously good-natured dog whose deep loyalty and strength earned it a place in American history.",
    origin: "United States", size: "medium" as const, temperament: "Confident, Good-Natured, Courageous", lifespan: "12-16 years", imageUrl: "https://images.dog.ceo/breeds/terrier-american/n02093428_10164.jpg", group: "Terrier", rarity: "uncommon" as const,
    personality: "Big-hearted gym buddy who'd never miss leg day",
    humanJob: "Personal trainer who cries at commercials",
    coffeeOrder: "Protein-heavy cold brew, extra scoop",
    ancestors: "Developed in America from the Staffordshire Bull Terrier and old bulldog stock, then bred larger and away from fighting into a family and show dog",
    funFact: "A Staffordshire-type dog named Sergeant Stubby became the most decorated war dog of WWI, capturing a German spy and warning troops of gas attacks",
    popCulture: "Petey with the ring around his eye in 'The Little Rascals' was an American Staffordshire-type Terrier and a national icon",
    energyLevel: 4, apartmentFriendly: 3, chaosLevel: 3,
    randomLore: "The AKC recognized the AmStaff in 1936, formally splitting it from the smaller Staffordshire Bull Terrier of England",
  },
  {
    id: "sussex-spaniel", name: "Sussex Spaniel",
    description: "The golden-liver slowpoke of the spaniels! A low, heavy-bodied gundog that plods deliberately through cover and is the only spaniel that barks while hunting.",
    origin: "England", size: "medium" as const, temperament: "Friendly, Merry, Calm", lifespan: "13-15 years", imageUrl: "https://images.dog.ceo/breeds/spaniel-sussex/n02102480_101.jpg", group: "Sporting", rarity: "legendary" as const,
    personality: "Gloriously slow gentleman who refuses to rush",
    humanJob: "Retired jazz bassist who takes life at half tempo",
    coffeeOrder: "Slow drip, savored over a long afternoon",
    ancestors: "Developed in Sussex, England in the late 1700s as a slow, methodical flushing spaniel for thick undergrowth on foot",
    funFact: "It's the only spaniel that habitually gives voice while working, so hunters on foot could follow it through dense brush by sound alone",
    popCulture: "Clussexx Three D Grinchy Glee, known as 'Stump,' won Best in Show at Westminster in 2009 at age ten — the oldest winner in the event's history",
    energyLevel: 2, apartmentFriendly: 4, chaosLevel: 2,
    randomLore: "The breed nearly went extinct twice — after WWII, only a handful survived thanks to a single dedicated breeder, Joy Freer",
  },
  {
    id: "bluetick-coonhound", name: "Bluetick Coonhound",
    description: "A cold-nosed night hunter with a mottled 'blue' coat! Famous for its determination on the coldest, oldest trails and a deep, ringing bawl.",
    origin: "United States", size: "large" as const, temperament: "Intelligent, Devoted, Determined", lifespan: "11-12 years", imageUrl: "https://images.dog.ceo/breeds/bluetick/n02088632_101.jpg", group: "Hound", rarity: "rare" as const,
    personality: "Stubborn night owl who follows his nose off cliffs",
    humanJob: "Overnight private eye who never drops a case",
    coffeeOrder: "Bottomless diner refills at 3 a.m.",
    ancestors: "Bred in the American South from English Foxhounds, French staghounds and the Grand Bleu de Gascogne for cold-trailing raccoons and larger game",
    funFact: "Its coat isn't truly blue — dense black ticking over a white base creates a mottled slate-blue effect that gives the breed its name",
    popCulture: "Smokey, the University of Tennessee's live mascot, is a Bluetick Coonhound whose famous howl echoes through Neyland Stadium",
    energyLevel: 4, apartmentFriendly: 2, chaosLevel: 3,
    randomLore: "Blueticks are prized 'cold-nosed' hounds, meaning they can pick up and follow scent trails that are hours or even days old",
  },
  {
    id: "irish-water-spaniel", name: "Irish Water Spaniel",
    description: "The clown of the spaniels! The tallest spaniel, crowned with a topknot of curls and finished with a bald 'rat tail' — a tireless, comical water retriever.",
    origin: "Ireland", size: "large" as const, temperament: "Playful, Hardworking, Brave", lifespan: "12-13 years", imageUrl: "https://images.dog.ceo/breeds/spaniel-irish/n02102973_1037.jpg", group: "Sporting", rarity: "rare" as const,
    personality: "Goofy curly comedian who loves a swim",
    humanJob: "Standup comic who's also a champion lifeguard",
    coffeeOrder: "Iced coffee splashed everywhere on purpose",
    ancestors: "Developed in Ireland in the 1830s by Justin McCarthy, likely blending older water spaniels, Poodles and possibly Portuguese Water Dogs",
    funFact: "Its signature 'rat tail' — thick and curly at the base then smooth and hairless toward the tip — is unlike any other breed's tail",
    popCulture: "Nicknamed the 'clown of the spaniel family' for its playful antics and quirky, curl-topped appearance",
    energyLevel: 4, apartmentFriendly: 2, chaosLevel: 3,
    randomLore: "Its dense, waterproof curly coat is nearly hypoallergenic and, unusually for a spaniel, sheds very little",
  },
  {
    id: "entlebucher-mountain-dog", name: "Entlebucher Mountain Dog",
    description: "The smallest of the four Swiss mountain dogs! A compact, muscular tricolor herder from the Entlebuch valley — fast, driven, and fiercely devoted.",
    origin: "Switzerland", size: "medium" as const, temperament: "Loyal, Energetic, Agile", lifespan: "11-13 years", imageUrl: "https://images.dog.ceo/breeds/entlebucher/n02108000_1044.jpg", group: "Herding", rarity: "rare" as const,
    personality: "Hyper-loyal alpine workaholic with a laser focus",
    humanJob: "Mountain rescue dispatcher who never clocks out",
    coffeeOrder: "Strong Swiss espresso, gulped between chores",
    ancestors: "One of the four ancient Sennenhund breeds descended from Roman-era mastiffs and Alpine farm dogs of Switzerland",
    funFact: "It's the smallest and quickest of the four Swiss Sennenhund breeds, historically used to drive cattle down steep alpine pastures",
    popCulture: "So rare that it was nearly lost — a 1913 census reportedly found only 16 remaining Entlebuchers in Switzerland",
    energyLevel: 5, apartmentFriendly: 2, chaosLevel: 3,
    randomLore: "The breed takes its name from the Entlebuch, a region in the Swiss cantons of Lucerne and Bern where it herded dairy cattle",
  },
  {
    id: "kuvasz", name: "Kuvasz",
    description: "A majestic white guardian of Hungarian kings! This large livestock protector once guarded royal estates and was so prized only nobility could own one.",
    origin: "Hungary", size: "large" as const, temperament: "Loyal, Protective, Fearless", lifespan: "10-12 years", imageUrl: "https://images.dog.ceo/breeds/kuvasz/bella_buddy.jpg", group: "Working", rarity: "legendary" as const,
    personality: "Regal bodyguard with an unshakeable sense of duty",
    humanJob: "Head of palace security, coldly professional",
    coffeeOrder: "Black, unsweetened, drunk while scanning exits",
    ancestors: "An ancient Hungarian flock guardian brought to the Carpathian Basin by the Magyars, later kept as a royal guard by King Matthias Corvinus",
    funFact: "King Matthias Corvinus of Hungary trusted his Kuvaszok more than his own guards and reportedly kept one by his side at all times",
    popCulture: "For centuries only aristocrats and royalty were permitted to own a Kuvasz, making it a living symbol of Hungarian nobility",
    energyLevel: 3, apartmentFriendly: 1, chaosLevel: 2,
    randomLore: "The breed was nearly wiped out during WWII — soldiers targeted them because the loyal dogs died defending their families' homes",
  },
  {
    id: "english-foxhound", name: "English Foxhound",
    description: "The classic pack hound of the British hunt! Bred over centuries for stamina and a musical voice, these hounds run in packs and rarely live as house pets.",
    origin: "England", size: "large" as const, temperament: "Gentle, Sociable, Tireless", lifespan: "10-13 years", imageUrl: "https://images.dog.ceo/breeds/hound-english/n02089973_1.jpg", group: "Hound", rarity: "legendary" as const,
    personality: "Sociable pack athlete who's lost without the team",
    humanJob: "Cross-country coach who lives for the group run",
    coffeeOrder: "Whatever the rest of the pack is having",
    ancestors: "Developed in England from the 1500s by blending Greyhounds, Bulldogs and Fox Terriers into a stamina hound for mounted fox hunting",
    funFact: "English Foxhounds are bred to hunt in large packs and are among the rarest breeds registered with the AKC, since most live in kennels of working hunts",
    popCulture: "Immortalized in centuries of English sporting art, always depicted streaming across the countryside in full cry behind mounted riders",
    energyLevel: 5, apartmentFriendly: 1, chaosLevel: 3,
    randomLore: "Detailed studbooks for English Foxhounds have been kept since the 18th century, making it one of the most meticulously recorded breeds in history",
  },
  {
    id: "black-and-tan-coonhound", name: "Black and Tan Coonhound",
    description: "A nose that hunts by scent alone! This striking black-and-tan hound trails raccoons and larger game with its head down, guided by a Bloodhound-like nose.",
    origin: "United States", size: "large" as const, temperament: "Easygoing, Bright, Even-Tempered", lifespan: "10-12 years", imageUrl: "https://images.dog.ceo/breeds/coonhound/n02089078_1021.jpg", group: "Hound", rarity: "rare" as const,
    personality: "Mellow tracker who lives entirely through his nose",
    humanJob: "Wine sommelier with a supernatural sense of smell",
    coffeeOrder: "Single-origin pour-over, chosen purely by aroma",
    ancestors: "Bred in America from the Talbot Hound, Bloodhound and Black and Tan Virginia Foxhound to trail raccoons and larger prey by scent",
    funFact: "It trails entirely by ground scent with long, low-hanging ears that sweep scent up toward its nose, much like its Bloodhound ancestors",
    popCulture: "In 1945 it became the first coonhound recognized by the AKC, opening the door for the other coonhound breeds",
    energyLevel: 4, apartmentFriendly: 2, chaosLevel: 3,
    randomLore: "Its rich black-and-tan pattern, including the tan 'pumpkin seed' dots above the eyes, comes straight from its Bloodhound heritage",
  },
  {
    id: "great-pyrenees", name: "Great Pyrenees",
    description: "A gentle white giant of the mountains! For centuries this majestic livestock guardian protected sheep from wolves and bears in the Pyrenees — calm, patient, and immense.",
    origin: "France", size: "large" as const, temperament: "Calm, Patient, Protective", lifespan: "10-12 years", imageUrl: "https://images.dog.ceo/breeds/pyrenees/beau1.jpg", group: "Working", rarity: "uncommon" as const,
    personality: "Serene fluffy mountain that would die for its flock",
    humanJob: "Night-watch shepherd who naps by day, patrols by night",
    coffeeOrder: "Decaf — needs to stay calm on the long night shift",
    ancestors: "An ancient flock-guarding breed of the Pyrenees Mountains between France and Spain, working alongside shepherds for thousands of years",
    funFact: "Many Great Pyrenees have double dewclaws on their hind legs, an unusual trait believed to help them navigate steep, snowy mountain terrain",
    popCulture: "Named the Royal Dog of France by the court of Louis XIV in 1675, and a beloved fixture of farms across the world today",
    energyLevel: 3, apartmentFriendly: 1, chaosLevel: 2,
    randomLore: "These guardians are nocturnal by instinct — they patrol and bark through the night, the exact hours predators are most likely to strike",
  },
  {
    id: "wire-fox-terrier", name: "Wire Fox Terrier",
    description: "The dapper show-ring superstar! With its wiry white coat and unstoppable spirit, this fox-bolting terrier has won more Westminster titles than any other breed.",
    origin: "England", size: "small" as const, temperament: "Alert, Confident, Gregarious", lifespan: "12-15 years", imageUrl: "https://images.dog.ceo/breeds/terrier-fox/n02095314_1033.jpg", group: "Terrier", rarity: "uncommon" as const,
    personality: "Dapper little show-off who owns every room",
    humanJob: "Award-winning actor who never stops networking",
    coffeeOrder: "Espresso, ordered loudly with full eye contact",
    ancestors: "Bred in England to bolt foxes from their dens during hunts, developed alongside the Smooth Fox Terrier from old British terrier stock",
    funFact: "The Wire Fox Terrier has won Best in Show at Westminster fifteen times, more than any other breed in the show's history",
    popCulture: "Asta in 'The Thin Man' films and the beloved Snowy (Milou) in the 'Tintin' comics are both Wire Fox Terriers",
    energyLevel: 5, apartmentFriendly: 3, chaosLevel: 4,
    randomLore: "The 1930s Asta films sparked such a craze for Wire Fox Terriers that demand briefly outstripped that of nearly every other breed in America",
  },
  {
    id: "kerry-blue-terrier", name: "Kerry Blue Terrier",
    description: "Ireland's 'Blue Devil'! Born black and maturing into a striking slate blue, this all-purpose Irish farm dog can herd, hunt, retrieve, and guard with equal flair.",
    origin: "Ireland", size: "medium" as const, temperament: "Smart, Alert, People-Oriented", lifespan: "12-15 years", imageUrl: "https://images.dog.ceo/breeds/terrier-kerryblue/n02093859_10.jpg", group: "Terrier", rarity: "rare" as const,
    personality: "Fiery Irish jack-of-all-trades with a soft coat",
    humanJob: "Farmer, poet, and part-time revolutionary",
    coffeeOrder: "Strong black tea, but he'll take the coffee too",
    ancestors: "An all-round working terrier from County Kerry, Ireland, legend links it to a blue dog that swam ashore from a shipwreck off the Irish coast",
    funFact: "Kerry Blue puppies are born black and gradually 'clear' to their signature blue-gray coat over the first year or two of life",
    popCulture: "Irish revolutionary leader Michael Collins was so fond of his Kerry Blue, Convict 224, that he once tried to have it named Ireland's national dog",
    energyLevel: 4, apartmentFriendly: 3, chaosLevel: 4,
    randomLore: "The breed was a symbol of Irish nationalism in the 1920s, and the first Irish Kennel Club show was organized partly to celebrate it",
  },
  {
    id: "briard", name: "Briard",
    description: "A heart wrapped in fur! This ancient French sheepdog hides keen intelligence and fierce devotion beneath a long, flowing coat and shaggy fringe over its eyes.",
    origin: "France", size: "large" as const, temperament: "Confident, Faithful, Loving", lifespan: "12 years", imageUrl: "https://images.dog.ceo/breeds/briard/n02105251_12.jpg", group: "Herding", rarity: "rare" as const,
    personality: "Devoted shaggy protector who can't see past its bangs",
    humanJob: "Bohemian sheep farmer with hair in their eyes",
    coffeeOrder: "Café au lait, sipped through a rustic beard",
    ancestors: "An ancient French herding and guardian breed dating to at least the Middle Ages, later used to move and protect flocks across the countryside",
    funFact: "Like the Great Pyrenees, the Briard has double dewclaws on each hind leg, a required breed trait tied to its mountain herding heritage",
    popCulture: "Thomas Jefferson and the Marquis de Lafayette both helped bring Briards to America, and the breed served as a French army messenger and Red Cross dog in WWI",
    energyLevel: 4, apartmentFriendly: 2, chaosLevel: 3,
    randomLore: "French shepherds sometimes said the Briard 'has a heart wrapped in fur,' capturing its blend of tenderness and tenacity",
  },
  {
    id: "brittany", name: "Brittany",
    description: "A compact, athletic bird dog with boundless energy! Once called the Brittany Spaniel, this French pointer-setter blend is one of the most versatile hunting dogs alive.",
    origin: "France", size: "medium" as const, temperament: "Bright, Fun-Loving, Upbeat", lifespan: "12-14 years", imageUrl: "https://images.dog.ceo/breeds/spaniel-brittany/n02101388_2064.jpg", group: "Sporting", rarity: "uncommon" as const,
    personality: "Bouncy optimist who treats every day as a hunt",
    humanJob: "Trail-running park ranger who's relentlessly cheerful",
    coffeeOrder: "Iced americano, downed mid-jog",
    ancestors: "Developed in the Brittany region of France as an all-purpose bird dog, blending the pointing and setting instincts of local spaniels and setters",
    funFact: "The AKC dropped 'Spaniel' from the name in 1982 because the Brittany points and works game more like a setter than a flushing spaniel",
    popCulture: "One of the most successful breeds in field trials, the Brittany has produced more dual champions — in both show and field — than almost any other sporting breed",
    energyLevel: 5, apartmentFriendly: 2, chaosLevel: 3,
    randomLore: "Some Brittanys are born with naturally short or absent tails, a genetic trait that occasionally shows up without any docking",
  },
  {
    id: "american-eskimo-dog", name: "American Eskimo Dog",
    description: "The sparkling white 'Dog Beautiful'! Despite its name, this fluffy German-descended spitz became a circus star in America, dazzling crowds with tricks and tightrope walks.",
    origin: "United States", size: "small" as const, temperament: "Playful, Perky, Smart", lifespan: "13-15 years", imageUrl: "https://images.dog.ceo/breeds/eskimo/n02109961_10021.jpg", group: "Non-Sporting", rarity: "uncommon" as const,
    personality: "Snowy little showman who lives for applause",
    humanJob: "Traveling circus performer with perfect white teeth",
    coffeeOrder: "Vanilla frappe with an absurd amount of whipped cream",
    ancestors: "Descended from white German Spitz dogs brought by immigrants, renamed the American Eskimo Dog during WWI as anti-German sentiment ran high",
    funFact: "'Eskies' were star attractions in American traveling circuses of the early 1900s, famous for performing tricks and walking tightropes",
    popCulture: "A circus Eskie named Stout's Pal Pierre was reportedly the first dog to walk a tightrope, wowing crowds across the country",
    energyLevel: 4, apartmentFriendly: 4, chaosLevel: 3,
    randomLore: "Despite the name, the breed has no connection to Eskimo or Arctic peoples — it was renamed purely for marketing and wartime politics",
  },
  {
    id: "appenzeller-sennenhund", name: "Appenzeller Sennenhund",
    description: "A whirlwind of a Swiss mountain dog! This medium tricolor herder is the most agile and high-energy of the four Sennenhund breeds, with a signature tightly curled tail.",
    origin: "Switzerland", size: "medium" as const, temperament: "Lively, Confident, Reliable", lifespan: "12-15 years", imageUrl: "https://images.dog.ceo/breeds/appenzeller/n02107908_1030.jpg", group: "Herding", rarity: "legendary" as const,
    personality: "Turbocharged alpine multitasker with a springy tail",
    humanJob: "Ski patrol lead who also runs the dairy",
    coffeeOrder: "Triple espresso, still not enough energy for this dog",
    ancestors: "One of the four ancient Swiss Sennenhund breeds, descended from Roman-era drover dogs used to herd cattle in the Appenzell region",
    funFact: "Its tightly curled tail carried over the back is a breed hallmark that sets it apart from its Sennenhund cousins",
    popCulture: "The breed was first described as distinct in 1853, and dedicated Swiss efforts saved it from being lost among the more famous Bernese",
    energyLevel: 5, apartmentFriendly: 1, chaosLevel: 4,
    randomLore: "Swiss forester Max Siber championed the Appenzeller in the 1890s, and a stud book was opened in 1906 to preserve the rare working breed",
  },
  {
    id: "chinese-crested", name: "Chinese Crested",
    description: "The elegant near-hairless charmer! This toy breed comes in two looks — a smooth 'Hairless' with tufts on head, feet, and tail, and a fully coated 'Powderpuff.'",
    origin: "China", size: "small" as const, temperament: "Affectionate, Alert, Lively", lifespan: "13-18 years", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/27/Chinese_crested_dog_picture.jpg", group: "Toy", rarity: "rare" as const,
    personality: "Devoted diva who velcros to your skin for warmth",
    humanJob: "Avant-garde fashion designer who feels the cold intensely",
    coffeeOrder: "Warm oat latte, cradled with both paws for heat",
    ancestors: "Likely descended from African or Mexican hairless dogs, later refined by Chinese traders who carried them aboard ships as ratters",
    funFact: "A single litter can contain both Hairless and Powderpuff puppies, since the two varieties are governed by the same dominant hairless gene",
    popCulture: "Chinese Cresteds have won the World's Ugliest Dog Contest many times, and one named Sam became a viral internet legend",
    energyLevel: 3, apartmentFriendly: 5, chaosLevel: 2,
    randomLore: "Hairless Cresteds can get sunburned and need sunscreen, and many owners dress them in sweaters because they chill easily",
  },
  {
    id: "soft-coated-wheaten-terrier", name: "Soft-Coated Wheaten Terrier",
    description: "The happy 'Wheatie'! An exuberant Irish farm terrier with a soft, silky wheat-colored coat and a signature move — the joyful full-body 'Wheaten greetin'.",
    origin: "Ireland", size: "medium" as const, temperament: "Happy, Friendly, Devoted", lifespan: "12-14 years", imageUrl: "https://images.dog.ceo/breeds/terrier-wheaten/clementine.jpg", group: "Terrier", rarity: "uncommon" as const,
    personality: "Bouncy golden optimist who greets you with a leap",
    humanJob: "Kindergarten teacher who's genuinely thrilled to see you",
    coffeeOrder: "Honey oat latte, warm and sweet like its coat",
    ancestors: "An old Irish farm terrier used for herding, guarding and vermin control, sharing roots with the Kerry Blue and Irish Terrier",
    funFact: "Unlike most terriers, the Wheaten has a soft, silky, single coat rather than a harsh double coat, and its puppies are born darker before clearing to wheaten",
    popCulture: "Famous for the 'Wheaten greetin'' — an ecstatic, jumping welcome — the breed was a common sight on Irish farms for over two centuries",
    energyLevel: 4, apartmentFriendly: 3, chaosLevel: 3,
    randomLore: "The Wheaten wasn't recognized in Ireland until St. Patrick's Day 1937, when the Irish Kennel Club fittingly granted it official status",
  },
  {
    id: "clumber-spaniel", name: "Clumber Spaniel",
    description: "The dignified heavyweight of the spaniels! Long, low, and massive-headed, this gentleman gundog moves at a deliberate roll and is the largest of the flushing spaniels.",
    origin: "England", size: "large" as const, temperament: "Mellow, Gentle, Loyal", lifespan: "10-12 years", imageUrl: "https://images.dog.ceo/breeds/clumber/n02101556_1018.jpg", group: "Sporting", rarity: "legendary" as const,
    personality: "Portly aristocrat who does everything at his own pace",
    humanJob: "Country estate butler, unflappably composed",
    coffeeOrder: "A pot of Earl Grey, actually — poured with ceremony",
    ancestors: "Developed on the Clumber Park estate of the Dukes of Newcastle in England, likely from Basset Hound and old spaniel stock",
    funFact: "It's the heaviest and most powerfully built of the spaniels, bred as a slow, methodical flushing dog for aristocratic shooting parties",
    popCulture: "A favorite of British royalty — King Edward VII and King George V both kept Clumber Spaniels in the royal kennels",
    energyLevel: 2, apartmentFriendly: 3, chaosLevel: 2,
    randomLore: "Legend claims the breed was moved from France to England during the French Revolution to protect the Duc de Noailles' kennel",
  },
  {
    id: "english-toy-terrier", name: "English Toy Terrier",
    description: "A sleek, miniature ratter with candle-flame ears! This black-and-tan toy is a shrunken version of the Manchester Terrier, once a champion at the sport of rat-killing.",
    origin: "England", size: "small" as const, temperament: "Alert, Keen, Affectionate", lifespan: "12-13 years", imageUrl: "https://images.dog.ceo/breeds/terrier-toy/20210422_193239-min.jpg", group: "Toy", rarity: "legendary" as const,
    personality: "Elegant tiny assassin with a delicate ego",
    humanJob: "Ballet dancer who used to work exterminating rats",
    coffeeOrder: "Precise little macchiato, poised and exact",
    ancestors: "A toy-sized descendant of the Black and Tan Terrier, bred down in Victorian England from the same stock as the Manchester Terrier",
    funFact: "Its erect, pointed 'candle flame' ears are a defining breed feature, and Victorian ratters used the tiny dogs in timed rat-killing contests in pits",
    popCulture: "A famous ratter named Tiny the Wonder reportedly killed 200 rats in under an hour in a London pit in the 1840s",
    energyLevel: 4, apartmentFriendly: 5, chaosLevel: 3,
    randomLore: "It's now one of the UK's most endangered native breeds, listed as vulnerable with only a small number of puppies registered each year",
  },
  {
    id: "basset-hound", name: "Basset Hound",
    description: "The droopy-eared scent-tracking legend! Short-legged and long-bodied with a nose second only to the Bloodhound, this laid-back hound follows a trail with unhurried determination.",
    origin: "France", size: "medium" as const, temperament: "Charming, Patient, Low-Key", lifespan: "12-13 years", imageUrl: "https://images.dog.ceo/breeds/hound-basset/n02088238_10005.jpg", group: "Hound", rarity: "uncommon" as const,
    personality: "Melancholy couch philosopher with a world-class nose",
    humanJob: "Jazz saxophonist who plays slow, sad ballads",
    coffeeOrder: "Cold brew, sipped very, very slowly",
    ancestors: "Bred in France ('bas' meaning low) from short-legged hound stock, likely tied to the St. Hubert Hound and the ancestors of the Bloodhound",
    funFact: "The Basset's sense of smell is second only to the Bloodhound's, and its long, drooping ears sweep scent up from the ground toward its nose",
    popCulture: "The face of Hush Puppies shoes for decades, plus Cleo from 'The People's Choice' and Fred Basset from the newspaper comic strip",
    energyLevel: 2, apartmentFriendly: 4, chaosLevel: 2,
    randomLore: "Its heavy body and short legs sit so low that Bassets are surprisingly poor swimmers and can struggle to keep their long ears dry",
  },
  {
    id: "japanese-spitz", name: "Japanese Spitz",
    description: "A cloud of pure white fluff! This cheerful companion spitz has a pointed fox-like face, a plush snow-white coat, and a devoted, playful personality.",
    origin: "Japan", size: "small" as const, temperament: "Alert, Affectionate, Playful", lifespan: "12-14 years", imageUrl: "https://images.dog.ceo/breeds/spitz-japanese/beet-001.jpg", group: "Non-Sporting", rarity: "rare" as const,
    personality: "Cheerful marshmallow with a fox's face and a big bark",
    humanJob: "Ski-resort receptionist who's suspiciously happy",
    coffeeOrder: "White chocolate mocha, matching the coat",
    ancestors: "Developed in Japan in the 1920s and 30s from imported white German Spitz and other white spitz-type dogs",
    funFact: "Despite its fluffy pure-white double coat, the Japanese Spitz is remarkably clean — dirt tends to fall off its non-sticky coat, and it rarely needs bathing",
    popCulture: "A beloved companion breed across Japan, Europe and Australia, often mistaken for a smaller cousin of the Samoyed or American Eskimo Dog",
    energyLevel: 3, apartmentFriendly: 5, chaosLevel: 2,
    randomLore: "The breed was carefully standardized after WWII by Japanese breeders, who set its final standard in 1948",
  },
  {
    id: "komondor", name: "Komondor",
    description: "The living mop! This massive Hungarian livestock guardian is covered head to tail in long, felted white cords that camouflage it among sheep and shield it from predators.",
    origin: "Hungary", size: "large" as const, temperament: "Steady, Fearless, Affectionate", lifespan: "10-12 years", imageUrl: "https://images.dog.ceo/breeds/komondor/n02105505_1024.jpg", group: "Working", rarity: "legendary" as const,
    personality: "Dreadlocked guardian who hides in the flock and strikes",
    humanJob: "Undercover bodyguard disguised as a rug",
    coffeeOrder: "Black coffee, if you can find its mouth under the cords",
    ancestors: "An ancient Hungarian flock guardian brought by the Magyars or nomadic Cumans, bred to blend in with and protect sheep",
    funFact: "Its heavy corded coat can weigh well over 15 pounds and lets the dog blend in with the flock while protecting it from both weather and predator bites",
    popCulture: "The Komondor's mop-like look inspired countless comparisons, and even Beck used one in album artwork; it also famously resembles a certain shaggy pop-culture look",
    energyLevel: 3, apartmentFriendly: 1, chaosLevel: 2,
    randomLore: "Komondor cords aren't groomed into place — the coat naturally felts as the soft undercoat tangles with the coarse outer coat as the dog matures",
  },
  {
    id: "pekingese", name: "Pekingese",
    description: "The lion dog of the imperial palace! For centuries this flat-faced toy was sacred to Chinese emperors, and stealing one was punishable by death.",
    origin: "China", size: "small" as const, temperament: "Affectionate, Regal, Stubborn", lifespan: "12-14 years", imageUrl: "https://images.dog.ceo/breeds/pekinese/n02086079_10059.jpg", group: "Toy", rarity: "uncommon" as const,
    personality: "Tiny emperor who expects to be carried everywhere",
    humanJob: "Retired monarch who refuses to acknowledge the abdication",
    coffeeOrder: "Imperial jasmine tea, served on a golden tray",
    ancestors: "An ancient Chinese breed cherished in the imperial court of the Tang dynasty and beyond, bred to resemble the Buddhist guardian lions",
    funFact: "Pekingese were sacred to Chinese royalty and commoners were forbidden to own them — stealing one from the palace was once a crime punishable by death",
    popCulture: "A Pekingese named Sun Yat Sen survived the sinking of the Titanic, and the breed has taken Best in Show at both Westminster and Crufts",
    energyLevel: 2, apartmentFriendly: 5, chaosLevel: 2,
    randomLore: "When British forces looted the Old Summer Palace in 1860, five Pekingese were taken to England — one was gifted to Queen Victoria and named, aptly, 'Looty'",
  },
  {
    id: "miniature-pinscher", name: "Miniature Pinscher",
    description: "The self-proclaimed 'King of Toys'! Fearless, high-stepping, and endlessly bold, the Min Pin struts like a tiny hackney horse and is no relation to the Doberman.",
    origin: "Germany", size: "small" as const, temperament: "Fearless, Energetic, Alert", lifespan: "12-16 years", imageUrl: "https://images.dog.ceo/breeds/pinscher-miniature/2013-08-23_21.38.32.jpg", group: "Toy", rarity: "uncommon" as const,
    personality: "Tiny tyrant with the swagger of a giant",
    humanJob: "Pint-sized CEO who genuinely runs the whole company",
    coffeeOrder: "Double espresso, no time to sit down",
    ancestors: "An old German ratting breed developed from the German Pinscher with Dachshund and Italian Greyhound influence, predating the Doberman",
    funFact: "Despite the resemblance, the Min Pin is NOT a miniature Doberman — the breed is far older, and it's the Doberman that came along centuries later",
    popCulture: "Nicknamed the 'King of Toys,' it's instantly recognizable by its prancing, high-stepping 'hackney' gait borrowed from carriage horses",
    energyLevel: 5, apartmentFriendly: 4, chaosLevel: 4,
    randomLore: "Its German name Zwergpinscher means 'dwarf biter,' a nod to its original job clearing stables and homes of rats",
  },
  {
    id: "australian-kelpie", name: "Australian Kelpie",
    description: "The tireless engine of the outback! This lean, athletic herder can work sheep all day in blistering heat and is famous for running across the backs of a packed flock.",
    origin: "Australia", size: "medium" as const, temperament: "Intelligent, Energetic, Devoted", lifespan: "10-13 years", imageUrl: "https://images.dog.ceo/breeds/kelpie/n02105412_1031.jpg", group: "Herding", rarity: "rare" as const,
    personality: "Relentless work fiend who cannot compute a day off",
    humanJob: "Marathon-running station hand who never stops moving",
    coffeeOrder: "Black long black, chugged on the move at sunrise",
    ancestors: "Developed in Australia from British collie-type sheepdogs brought by settlers, bred for stamina and independence in the harsh outback",
    funFact: "Kelpies are famous for 'backing' — running across the backs of tightly packed sheep to move through or reach the front of a flock",
    popCulture: "A Kelpie inspired the film 'Red Dog,' based on a real wandering dog who became a legend across Western Australia's mining communities",
    energyLevel: 5, apartmentFriendly: 1, chaosLevel: 3,
    randomLore: "The breed is named after 'Kelpie,' an early bitch named for the shape-shifting water spirit of Scottish and Celtic folklore",
  },
];
